### ISSUE TITLE
Ensure php 5.3, 5.4, 5.5 are working via phpunit

### ISSUE THREAD

**Issue by kdocki** [CodeSleeve/asset-pipeline#22]
I don't know if php 5.3 is working since I've only tested on php 5.4... so I'd like to test this in other php envs ... want to test using... 

`.travis.yml`

``` yml
language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
```
