### ISSUE TITLE
Requiring tree broke the combination

### ISSUE THREAD

**Issue by RomainLanz** [CodeSleeve/asset-pipeline#230]
Hi everyone,

when I put `require_tree .` on `application.css` or `application.js` it's broke the combination and write directly SASS content on the final content.

````scss
[....]
.fa-meanpath:before{content:"\f20c"}
@import "pages/login";
body {
  padding-top: 70px; }

/**
 *= require bootstrap
 *= require font-awesome
 *= require main
 *= require_tree .
 */


@import "modules/all";
body {
  padding-top: 70px;
  background-color: red; }
````
